services:
  - type: web
    name: travelbrain-php
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DB_DRIVER
        value: mongo
      - key: MONGO_DB
        value: travel_brain
      - key: MONGO_URI
        fromSecret: mongo_uri
      - key: OPENWEATHER_API_KEY
        fromSecret: openweather_api_key
      - key: APP_ENV
        value: production
      - key: TZ
        value: America/Guayaquil
      - key: MAPBOX_TOKEN
        value: pk.eyJ1Ijoic3JqY2JtIiwiYSI6ImNtZ3g0eGV5NDAwZzYya3BvdmFveWU2dnEifQ.yYCrLmlo9lW-AJf56akVCw
      # Opcionales para currency
      # - key: CURRENCY_PROVIDER
      #   value: erapi
      # - key: OPENEXCHANGERATES_APP_ID
      #   fromSecret: openexchangerates_app_id

secretFiles: []